version: "3"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test_app
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  test_db_data: {}
